[build]
  base = "framework"
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_CONTENT_PACKAGE = "board-ready"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
